name: build and test feature branch
on: 
  push:
    branches:
      - "feature/*"
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull and checkout from git repository
        run: 
          echo "pulling and checking out from git repository"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: ng test

      - name: Build Angular app
        run: ng build --prod